data:
   name: sciplex
   file_path: /dccstor/storage01/datasets/scrna-sciplex3/hvg.h5ad
   batch_size: 512
   split: [0.8, 0.2]
   seed: 42
   drug_col: drug-dose
   drug_condition: givinostat-10
   control_condition: control-0
   ae: true

conditions: [givinostat-10 , givinostat-100, givinostat-1000, givinostat-10000]

model:
   hidden_dims: [512, 512]
   latent_dim: 50
   data_dim: 1000
   seed: 42
   act_fn: gelu

optim:
   lr: 1.0e-4
   optimizer: adamw
   kwargs:
      weight_decay: 1.0e-5

training:
  n_epochs: 50
  ckpt: false
  model_dir: models/
