data:
  name: 4i
  file_path: /dccstor/storage01/datasets/4i/8h.h5ad
  drugs_path: /dccstor/storage01/datasets/4i/drugs.txt
  features: /dccstor/storage01/datasets/4i/features.txt
  batch_size: 256
  split: [0.8, 0.2]
  drug_col: drug
  drug_condition: ixazomib
  control_condition: control
  ae: true

model:
   hidden_dims: [32, 32]
   latent_dim: 8
   data_dim: 48
   seed: 42
   act_fn: gelu
   cpkt: false

optim:
   lr: 1.0e-4
   optimizer: adamw
   kwargs:
      weight_decay: 1.0e-5

training:
  n_epochs: 50
  model_dir: models/
