logger_path: conditional-monge/logs/cmonge/CD4_11d_FuncScore.yml

data:
  name: car
  file_path: conditional-monge/CD4.h5ad
  drugs_path: conditional-monge/CAR_variants.txt
  features: conditional-monge/functional_and_score_genes.txt
  batch_size: 256
  split: [0.8, 0.2, 0]
  drug_col: CAR_Variant
  drug_condition: IL15RA-CD28-z
  control_condition: NA-NA-NA
  ae: false
  seed: 42

condition:
  mode: homogeneous
  conditions: [41BB-41BB-z, 41BB-CD28-z, 41BB-CD40-z, 41BB-CTLA4-z, 
      41BB-IL15RA-z, 41BB-NA-z, CD28-41BB-z, CD28-CD28-z,
      CD28-CD40-z, CD28-CTLA4-z, CD28-IL15RA-z, CD28-NA-z,
      CD40-41BB-z, CD40-CD28-z, CD40-CD40-z, CD40-CTLA4-z,
      CD40-IL15RA-z, CD40-NA-z, CTLA4-41BB-z, CTLA4-CD28-z,
      CTLA4-CD40-z, CTLA4-CTLA4-z, CTLA4-IL15RA-z, CTLA4-NA-z,
      IL15RA-41BB-z, IL15RA-CD28-z, IL15RA-CD40-z, IL15RA-CTLA4-z,
      IL15RA-IL15RA-z, IL15RA-NA-z, NA-NA-NA, NA-NA-z]
  split: [0.8, 0.2, 0]

model:
  method: monge

  fitting_loss:
    name: sinkhorn
    kwargs:
      epsilon_fitting: 1

  regularizer:
    name: monge
    kwargs:
      epsilon_regularizer: 1.0e-2
      cost: euclidean

  optim:
    lr: 1.0e-4
    name: adamw
    grad_acc_steps: 1
    kwargs:
      weight_decay: 1.0e-5
  mlp:
    dim_hidden: [64, 64, 64, 64]
    dim_data: 82
    dim_cond: 11
    dim_cond_map: 50

  checkpointing: false
  checkpointing_args:
    checkpoint_dir: conditional-monge/Outputs/cmonge/CD4_11d_FuncScore/
    checkpoint_crit: sinkhorn_div

  embedding:
    name: embed_11d
    model_dir: conditional-monge/embedding
    checkpoint: true
  
  num_train_iters: 10000
  seed: 42